services:
  jekyll:
    build: .
    ports:
      - "8080:8080"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll:cached
      - jekyll_site:/srv/jekyll/_site
    environment:
      - JEKYLL_ENV=development

volumes:
  jekyll_site:
