name: Lighthouse Badge

on:
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Lighthouse
        uses: MyActionWay/lighthouse-badger-action@v2.2
        with:
          urls: 'https://www.farhadallian.co.uk'
          audit_type: 'desktop'
          badges_args: '-b pagespeed -o lighthouse_results -r'
          
      - name: Commit Results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add lighthouse_results
          git commit -m "Update Lighthouse badge" || exit 0
          git push